export const AUTH = 'AUTH'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
export const REGISTER = 'REGISTER'
export const REGISTER_START = 'REGISTER_START'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const RESET_ERROR = 'RESET_ERROR'



export const FETCH_ARTICLES = 'FETCH_ARTICLES';
export const FETCH_ARTICLES_START = 'FETCH_ARTICLES_START';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAIL = 'FETCH_ARTICLES_FAIL';

export const FETCH_ARTICLE_BY_ID = 'FETCH_ARTICLE_BY_ID';
export const FETCH_ARTICLE_BY_ID_START = 'FETCH_ARTICLE_BY_ID_START';
export const FETCH_ARTICLE_BY_ID_SUCCESS = 'FETCH_ARTICLE_BY_ID_SUCCESS';
export const FETCH_ARTICLE_BY_ID_FAIL = 'FETCH_ARTICLE_BY_ID_FAIL';